stages:
- Flame

variables:
  RESULTS_DIR: "results"
  
Flame:
  stage: Flame
  image: ruby
  before_script:
  - apt-get update
  - apt-get install -y git
  script:
  - git clone https://github.com/blazeinfosec/Flame.git
  - gem install nokogiri
  - gem install OptionParser
  - cd Flame
  - ls -al
  - ./flame.rb --file ../report.xml --tool-name Owaspzap --siem Splunk --username XXX --password XXX --server 192.168.2.10 --port 8089 --token XXX --source Flame
  retry: 2
  allow_failure: true
  artifacts:
    paths:
    - report.xml
